include:
#   - docker-compose.tracing.yaml
#   - docker-compose.web.yaml
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-example}
    logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    network_mode: host
    restart: unless-stopped
    ports:
      - "6333:6333" 
    environment:
      - RUN_MODE=production
      - QDRANT__GPU__INDEXING=1 
    logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"

volumes:
  mongodb-data:
