include:
#   - docker-compose.tracing.yaml
#   - docker-compose.web.yaml
services:
  mongodb_service:
    container_name: mongodb_service
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-example}
    logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333" 
    environment:
      - RUN_MODE=production
      - QDRANT__GPU__INDEXING=1 
    logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
  
  backend:
    build:
      # to access root directory
      context: . 
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    env_file: ".env"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URL=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-example}@mongodb_service:27017/?authSource=admin
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - mongodb_service
      - qdrant

volumes:
  mongodb-data:
