include:
#   - docker-compose.tracing.yaml
#   - docker-compose.web.yaml
services:
  mongodb_service:
    container_name: mongodb_service
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-example}
    logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333" 
    environment:
      - RUN_MODE=production
      - QDRANT__GPU__INDEXING=1 
    logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      # to access root directory
      context: . 
      dockerfile: backend/Dockerfile
    ports:
      - "8080"
    env_file: ".env"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URL=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-example}@mongodb_service:27017/?authSource=admin
      - FRONTEND_ORIGIN_URL=http://localhost:3000
      - LANGFUSE_HOST=http://langfuse-web:3000
      - LANGFUSE_ENABLED=False

    depends_on:
      - mongodb_service
      - qdrant
      - langfuse-web
  
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - backend
    ports:
      - "80:80"  
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro  


volumes:
  mongodb-data:
