RESUME_GEN_PROMPT = """ """

JD_GEN_PROMPT = """ """

RESUME_EVAL_PROMPT = """ """

JD_EVAL_PROMPT = """ """

RESUME_DRAFT_GEN_PROMPT = """ """

RESUME_DRAFT_EVAL_TRUTHFUL = """ """

RESUME_DRAFT_EVAL_ALIGN = """ """

RESUME_AI_CRITIC_PROMPT = """ """

RESUME_GEMINI_GEN_PROMPT = """ """
